### ISSUE TITLE
Error Running Message_windows.py

### ISSUE THREAD

**Issue by colineberly** [satendrapandeymp/Facebook_message_download#2]
Hi, first of all thanks for this. So, when trying to fire up on Windows, I get the following error: 

```
  File "Message_windows.py", line 40
    flag += 1
            ^
TabError: inconsistent use of tabs and spaces in indentation
```
I can't proceed past this point.

**Comment by colineberly** [comment]
After fixing the spacing issue, I get this:

```
File "Message_windows.py", line 243
    print num, " messages had been downloaded from today till - ",datetime.utcfromtimestamp(float(ti
mestamp)/1000).strftime('%d-%m-%Y')
            ^
SyntaxError: invalid syntax
```

**Comment by satendrapandeymp** [comment]
Well, I have written this script for python 2.x that's why it's throwing errors in python 3.x

Maybe on this weekend I will make it available for both of the python versions.
